services:
  main:
    build: .
    volumes:
      - ${PWD}:/home
      - ${PWD}/tests/test8.json:/var/rinha/source.rinha.json
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M